# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sudo: false
env:
  global:
    - MONGODB=3.6.4
  matrix:
    - MODULE=oak-store-document PROFILE="-PintegrationTesting" UT=""
before_install:
  - wget -N http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O $HOME/.mongodb/mongodb.tgz
  - tar --skip-old-files -C $HOME/.mongodb -xf $HOME/.mongodb/mongodb.tgz
  - mkdir -p target/mongodb/data
  - cd target/mongodb
  - virtualenv mtools
  - source mtools/bin/activate
  - pip install --upgrade pip
  - pip install pymongo mtools
  - mlaunch init --replicaset --binarypath $HOME/.mongodb/mongodb-linux-x86_64-${MONGODB}/bin --dir ${HOME}/target/mongodb/data
  - cd $TRAVIS_BUILD_DIR
install:  mvn --batch-mode -DskipTests -Dbaseline.skip=true install -pl :${MODULE} -am -nsu
script:   mvn --batch-mode clean verify -Dbaseline.skip=true ${UT} ${PROFILE} -Dnsfixtures=DOCUMENT_NS -pl :${MODULE} -nsu
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.mongodb
addons:
  apt:
    packages:
      - python
      - python-dateutil
      - python-psutil
      - python-pip
      - python-virtualenv
notifications:
  email: false
