name: Java CI with Maven

on:
  push:
    branches: [ github-workflow ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [oak-store-document, oak-lucene, oak-it, oak-run, oak-upgrade, oak-pojosr, oak-it-osgi]
        profile: [-PintegrationTesting]
        ut: ['']
        include:
          - module: oak-jcr
            profile: '-PintegrationTesting'
            ut: '-Dsurefire.skip.ut=true'
          - module: oak-jcr
            profile: ''
            ut: ''
    services:
      mongodb:
        image: mongo:4.0
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build dependencies
      run: mvn -B -DskipTests -Dbaseline.skip=true -T 1C -am -nsu -pl :${{ matrix.module }} install
    - name: Test module
      run: mvn -B -nsu -Dnsfixtures=DOCUMENT_NS ${{ matrix.ut }} ${{ matrix.profile }} -pl :${{ matrix.module }} verify
    - name: Upload to Codecov
      run: bash <(curl -s https://codecov.io/bash)
